name: unieventos
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  image_picker: ^1.0.5
  image_cropper: ^11.0.0
  image: ^4.1.7
  intl: ^0.20.2
  flutter_svg: ^2.0.10
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  
  # Firebase & Push Notifications
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^17.1.0
  
  # State Management
  riverpod: ^3.1.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  connectivity_plus: ^4.0.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Utils
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1
  
  # Code Generation
  build_runner: ^2.4.15
  riverpod_generator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/splash/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/unieventos_icon.png"
  adaptive_icon_background: "#0D1117"
  adaptive_icon_foreground: "assets/icon/unieventos_icon.png"

flutter_native_splash:
  color: "#0D1117"
  image: assets/splash/unieventos_icon.png

  android_12:
    color: "#0D1117"
    image: assets/splash/unieventos_icon.png
